package isabelle


import scala.scalajs.js.annotation.JSExport
import scala.scalajs.js.annotation.JSExportTopLevel


@JSExportTopLevel("Scalajs_Example")
object Scalajs_Example {
  val term = {
    import XML.Elem
    import XML.Text

    List(Elem(
      Markup("language", List(("name", "term"), ("symbols", "true"), ("antiquotes", "false"), ("delimited", "false"))), List(Elem(
        Markup("block", Nil), List(Elem(
          Markup("notation", List(("name", "\\<Longrightarrow>"), ("kind", "infix"))), List(Elem(
            Markup("block", Nil), List(
              Elem(
                Markup("notation", List(("kind", "judgment"))), List(Elem(
                  Markup("block", Nil), List(Elem(
                    Markup("notation", List(("kind", "application"))), List(Elem(
                      Markup("block", List(("indent", "1"))), List(
                        Elem(
                          Markup("xml_elem", List(("xml_name", "typing"))), List(
                            Elem(
                              Markup("xml_body", Nil), List(Elem(
                                Markup("block", Nil), List(Elem(
                                  Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                    Markup("block", Nil), List(
                                      Elem(
                                        Markup("block", List(("indent", "1"))), List(
                                          Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("("))))))), Elem(
                                            Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                              Markup("block", Nil), List(
                                                Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text(")"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("entity", List(("ref", "69596"), ("def_line", "88"), ("def_offset", "2979"), ("def_end_offset", "2983"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.bool"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("bool"))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "295990"), ("def_line", "151"), ("def_offset", "3734"), ("def_end_offset", "3737"), ("def_file", "~~/src/HOL/Fun.thy"), ("def_id", "30"), ("name", "Fun.inj"), ("kind", "constant"))), List(Elem(Markup("const", Nil), List(Text("inj"))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                          Markup("xml_elem", List(("xml_name", "typing"))), List(
                            Elem(
                              Markup("xml_body", Nil), List(Elem(
                                Markup("block", Nil), List(Elem(
                                  Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                    Markup("block", Nil), List(
                                      Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?f"))))))))))))))))), Text(" "), Elem(
                Markup("xml_elem", List(("xml_name", "typing"))), List(
                  Elem(
                    Markup("xml_body", Nil), List(Elem(
                      Markup("block", Nil), List(Elem(
                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                          Markup("block", Nil), List(
                            Elem(Markup("entity", List(("ref", "202"), ("def_line", "76"), ("def_file", "pure_thy.ML"), ("name", "prop"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("prop"))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "202"), ("def_line", "76"), ("def_file", "pure_thy.ML"), ("name", "prop"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("prop"))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("entity", List(("ref", "202"), ("def_line", "76"), ("def_file", "pure_thy.ML"), ("name", "prop"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("prop"))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "320"), ("def_line", "232"), ("def_file", "pure_thy.ML"), ("name", "Pure.imp"), ("kind", "constant"))), List(Elem(Markup("const", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Longrightarrow>"))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                Markup("notation", List(("kind", "judgment"))), List(Elem(
                  Markup("block", Nil), List(Elem(
                    Markup("notation", List(("name", "="), ("kind", "infix"))), List(Elem(
                      Markup("block", Nil), List(
                        Elem(
                          Markup("notation", List(("kind", "application"))), List(Elem(
                            Markup("block", List(("indent", "1"))), List(
                              Elem(
                                Markup("xml_elem", List(("xml_name", "typing"))), List(
                                  Elem(
                                    Markup("xml_body", Nil), List(Elem(
                                      Markup("block", Nil), List(Elem(
                                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                          Markup("block", Nil), List(
                                            Elem(
                                              Markup("block", List(("indent", "1"))), List(
                                                Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("("))))))), Elem(
                                                  Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                    Markup("block", Nil), List(
                                                      Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text(")"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                              Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                Markup("block", Nil), List(
                                                  Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "5180732"), ("def_offset", "12"), ("def_end_offset", "22"), ("def_id", "-2924"), ("name", "Multiset.image_mset"), ("kind", "constant"))), List(Elem(Markup("const", Nil), List(Text("image_mset"))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                Markup("xml_elem", List(("xml_name", "typing"))), List(
                                  Elem(
                                    Markup("xml_body", Nil), List(Elem(
                                      Markup("block", Nil), List(Elem(
                                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                          Markup("block", Nil), List(
                                            Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?f"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                Markup("block", List(("indent", "1"))), List(
                                  Elem(
                                    Markup("xml_elem", List(("xml_name", "typing"))), List(
                                      Elem(
                                        Markup("xml_body", Nil), List(Elem(
                                          Markup("block", Nil), List(Elem(
                                            Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                              Markup("block", Nil), List(
                                                Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                                  Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                    Markup("block", Nil), List(
                                                      Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "152578"), ("def_line", "197"), ("def_offset", "5411"), ("def_end_offset", "5416"), ("def_label", "command.class"), ("def_file", "~~/src/HOL/Groups.thy"), ("def_id", "20"), ("name", "Groups.minus_class.minus"), ("kind", "constant"))), List(Elem(Markup("const", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("("))))))))))), Elem(
                                    Markup("notation", List(("name", "-"), ("kind", "infix"))), List(Elem(
                                      Markup("block", Nil), List(
                                        Elem(
                                          Markup("xml_elem", List(("xml_name", "typing"))), List(
                                            Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?A"))))))))), Text(" "), Elem(
                                          Markup("xml_elem", List(("xml_name", "typing"))), List(
                                            Elem(
                                              Markup("xml_body", Nil), List(Elem(
                                                Markup("block", Nil), List(Elem(
                                                  Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                    Markup("block", Nil), List(
                                                      Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                          Markup("block", Nil), List(
                                                            Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "152578"), ("def_line", "197"), ("def_offset", "5411"), ("def_end_offset", "5416"), ("def_label", "command.class"), ("def_file", "~~/src/HOL/Groups.thy"), ("def_id", "20"), ("name", "Groups.minus_class.minus"), ("kind", "constant"))), List(Elem(Markup("const", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("-"))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                          Markup("xml_elem", List(("xml_name", "typing"))), List(
                                            Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?B"))))))))))))), Elem(
                                    Markup("xml_elem", List(("xml_name", "typing"))), List(
                                      Elem(
                                        Markup("xml_body", Nil), List(Elem(
                                          Markup("block", Nil), List(Elem(
                                            Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                              Markup("block", Nil), List(
                                                Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                                  Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                    Markup("block", Nil), List(
                                                      Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "152578"), ("def_line", "197"), ("def_offset", "5411"), ("def_end_offset", "5416"), ("def_label", "command.class"), ("def_file", "~~/src/HOL/Groups.thy"), ("def_id", "20"), ("name", "Groups.minus_class.minus"), ("kind", "constant"))), List(Elem(Markup("const", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text(")"))))))))))))))))), Text(" "), Elem(
                          Markup("xml_elem", List(("xml_name", "typing"))), List(
                            Elem(
                              Markup("xml_body", Nil), List(Elem(
                                Markup("block", Nil), List(Elem(
                                  Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                    Markup("block", Nil), List(
                                      Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                          Markup("block", Nil), List(
                                            Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("entity", List(("ref", "69596"), ("def_line", "88"), ("def_offset", "2979"), ("def_end_offset", "2983"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.bool"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("bool"))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69656"), ("def_line", "93"), ("def_offset", "3122"), ("def_end_offset", "3124"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.eq"), ("kind", "constant"))), List(Elem(Markup("const", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("="))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                          Markup("notation", List(("name", "-"), ("kind", "infix"))), List(Elem(
                            Markup("block", Nil), List(
                              Elem(
                                Markup("notation", List(("kind", "application"))), List(Elem(
                                  Markup("block", List(("indent", "1"))), List(
                                    Elem(
                                      Markup("xml_elem", List(("xml_name", "typing"))), List(
                                        Elem(
                                          Markup("xml_body", Nil), List(Elem(
                                            Markup("block", Nil), List(Elem(
                                              Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                Markup("block", Nil), List(
                                                  Elem(
                                                    Markup("block", List(("indent", "1"))), List(
                                                      Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("("))))))), Elem(
                                                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                          Markup("block", Nil), List(
                                                            Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text(")"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                                    Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                      Markup("block", Nil), List(
                                                        Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "5180732"), ("def_offset", "12"), ("def_end_offset", "22"), ("def_id", "-2924"), ("name", "Multiset.image_mset"), ("kind", "constant"))), List(Elem(Markup("const", Nil), List(Text("image_mset"))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                      Markup("xml_elem", List(("xml_name", "typing"))), List(
                                        Elem(
                                          Markup("xml_body", Nil), List(Elem(
                                            Markup("block", Nil), List(Elem(
                                              Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                Markup("block", Nil), List(
                                                  Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?f"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                      Markup("xml_elem", List(("xml_name", "typing"))), List(
                                        Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?A"))))))))))))), Text(" "), Elem(
                                Markup("xml_elem", List(("xml_name", "typing"))), List(
                                  Elem(
                                    Markup("xml_body", Nil), List(Elem(
                                      Markup("block", Nil), List(Elem(
                                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                          Markup("block", Nil), List(
                                            Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                              Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                Markup("block", Nil), List(
                                                  Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "152578"), ("def_line", "197"), ("def_offset", "5411"), ("def_end_offset", "5416"), ("def_label", "command.class"), ("def_file", "~~/src/HOL/Groups.thy"), ("def_id", "20"), ("name", "Groups.minus_class.minus"), ("kind", "constant"))), List(Elem(Markup("const", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("-"))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                Markup("notation", List(("kind", "application"))), List(Elem(
                                  Markup("block", List(("indent", "1"))), List(
                                    Elem(
                                      Markup("xml_elem", List(("xml_name", "typing"))), List(
                                        Elem(
                                          Markup("xml_body", Nil), List(Elem(
                                            Markup("block", Nil), List(Elem(
                                              Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                Markup("block", Nil), List(
                                                  Elem(
                                                    Markup("block", List(("indent", "1"))), List(
                                                      Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("("))))))), Elem(
                                                        Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                          Markup("block", Nil), List(
                                                            Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text(")"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(
                                                    Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                      Markup("block", Nil), List(
                                                        Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "5180732"), ("def_offset", "12"), ("def_end_offset", "22"), ("def_id", "-2924"), ("name", "Multiset.image_mset"), ("kind", "constant"))), List(Elem(Markup("const", Nil), List(Text("image_mset"))))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                      Markup("xml_elem", List(("xml_name", "typing"))), List(
                                        Elem(
                                          Markup("xml_body", Nil), List(Elem(
                                            Markup("block", Nil), List(Elem(
                                              Markup("notation", List(("name", "\\<Rightarrow>"), ("kind", "infix"))), List(Elem(
                                                Markup("block", Nil), List(
                                                  Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(Markup("entity", List(("ref", "198"), ("def_line", "75"), ("def_file", "pure_thy.ML"), ("name", "fun"), ("kind", "type_name"))), List(Elem(Markup("tconst", List(("syntax", "true"))), List(Elem(Markup("delimiter", Nil), List(Text("\\<Rightarrow>"))))))), Text(" "), Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'b"))))))))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?f"))))))))), Elem(Markup("break", List(("width", "1"))), List(Text(" "))), Elem(
                                      Markup("xml_elem", List(("xml_name", "typing"))), List(
                                        Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("notation", List(("kind", "type_application"))), List(Elem(Markup("xml_elem", List(("xml_name", "sorting"))), List(Elem(Markup("xml_body", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("entity", List(("ref", "69444"), ("def_line", "76"), ("def_offset", "2580"), ("def_end_offset", "2584"), ("def_file", "~~/src/HOL/HOL.thy"), ("def_id", "12"), ("name", "HOL.type"), ("kind", "class"))), List(Elem(Markup("tclass", Nil), List(Text("type"))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("tvar", Nil), List(Text("?'a"))))))))), Text(" "), Elem(Markup("entity", List(("ref", "5142756"), ("def_offset", "12"), ("def_end_offset", "20"), ("def_id", "-482"), ("name", "Multiset.multiset"), ("kind", "type_name"))), List(Elem(Markup("tconst", Nil), List(Text("multiset"))))))))))), Elem(Markup("block", Nil), List(Elem(Markup("block", Nil), List(Elem(Markup("var", Nil), List(Text("?B"))))))))))))))))))))))))))))))))))
  }

  @JSExport
  def pretty_formatted(width: Double): String = Pretty.string_of(term, margin = width)
}